apiVersion: v1
kind: Service
metadata:
  labels:
    app: testnode
    track: canary
  name: testnode-canary
spec:
  ports:
    - nodePort: 36001
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: testnode
    track: canary
  type: NodePort
