apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: testnode
    track: canary
  name: testnode-canary
spec:
  replicas: 1
  selector:
    app: testnode
    track: canary
  template:
    metadata:
      labels:
        app: testnode
        track: canary
    spec:
      containers:
        - image: duttadeep55/test-node:2.0
          name: testnode
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
        - image: redis:2.8.22
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
