apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: testnode
    track: stable
    version: v2
  name: testnode-v2
spec:
  replicas: 5
  selector:
    app: testnode
    track: stable
    version: v2
  template:
    metadata:
      labels:
        app: testnode
        track: stable
        version: v2
    spec:
      containers:
        - image: duttadeep55/test-node:2.0
          name: testnode
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /version
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
