apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-node
    track: canary
  name: test-node
spec:
  replicas: 4
  selector:
    matchLabels:
      run: test-node
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: test-node
        track: canary
    spec:
      containers:
      - name: test-node
        image: duttadeep55/test-node:2.0
        ports:
        - containerPort: 8080