apiVersion: v1
kind: Service
metadata:
  name: test-node-svc
  labels:
    app: test-node
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: test-node
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-node
    track: stable
  name: test-node
spec:
  replicas: 4
  selector:
    matchLabels:
      run: test-node
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: test-node
        track: stable
    spec:
      containers:
      - name: test-node
        image: duttadeep55/test-node:1.0
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
